---
- name: Add nginx repository
  yum_repository:
    name: Nginx
    description: Nginx Repository
    baseurl: http://nginx.org/packages/centos/{{ ansible_distribution_major_version }}/$basearch/

- name: Add Nginx repository key
  rpm_key:
    key: http://nginx.org/keys/nginx_signing.key  

- name: Install nginx packages
  yum: 
    name: nginx
    state: present
    update_cache: true
  notify: restart nginx

- name: Create systemd override directory for nginx service
  file:
    path: /etc/systemd/system/nginx.service.d
    state: directory

- name: Copy override.conf
  copy:
    src: override.conf
    dest: /etc/systemd/system/nginx.service.d/override.conf

- name: Configure selinux
  selinux_permissive:
    name: httpd_t
    permissive: true

- name: Ensure nginx to be started after reboot
  service: 
    name: nginx
    enabled: yes
    state: started

- name: Check if firewalld is running
  command: systemctl status firewalld
  ignore_errors: yes
  changed_when: false
  register: firewalld_status

- name: Open ports for http
  firewalld:
    zone: public
    port: "{{ nginx_bind_port_http }}/tcp"
    permanent: true
    state: enabled
  when: firewalld_status is succeeded

- name: Open ports for https
  firewalld:
    zone: public
    port: "{{ nginx_bind_port_http }}/tcp"
    permanent: true
    state: enabled
  when: firewalld_status is succeeded
